/*
 * This file is part of USBscope50 Software.
 *
 *   USBscope50 Software is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   any later version.
 *
 *   USBscope50 Software is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   A copy of the GNU General Public License should be included
 *   along with USBscope50 Software.  If not, see <http://www.gnu.org/licenses/>.
 *
 * 
 */


package usbscope50software;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author  ana
 */
public class Tutorial extends javax.swing.JFrame {
    
    ImageIcon ElanLogo = new ImageIcon(getClass().getResource("/usbscope50software/Images/elan-logo.jpg"));
    ImageIcon AKIPLogo = new ImageIcon(getClass().getResource("/usbscope50software/Images/AKIP-logo.jpg"));
    String Cr = System.getProperty("line.separator");
    /** Creates new form Tutorial */
    public Tutorial() {
        initComponents();
        setLocation(0,0);                            //put form on the centre of the screen
        
        KeyStroke escape = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,0,false);
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escape, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
        
        TutorialClose.grabFocus();
        
    }
    
    Action escapeAction = new AbstractAction() {

        public void actionPerformed(ActionEvent e) {
            dispose();
        }
    };
        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea1.setCaretPosition(0);
        TutorialClose = new javax.swing.JButton();

        setTitle("USBscope50 Tutorial Probe Compensation Waveform");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(4);
        jTextArea1.setText("\tHi." + Cr + Cr + "\t" + USBscope50_Main.productID + " USB Tutorial is provided to help you " + Cr +
            "\tstart using and enjoying " + USBscope50_Main.companyID + "s USB scope quickly." + Cr + Cr +
            "\tAll you need is one " + USBscope50_Main.productID + " and one scope probe." + Cr + Cr + 
            "\tSelect tab labelled Ch1 on the screen. Move right or left" + Cr +
            "\tarrow buttons on this tab so that the label in the middle " + Cr +
            "\tof the arrows says 100 us/div." + Cr +
            "\tBy moving up or down arrows set vots per division " + Cr +
            "\tto 500 mV/div. Volts per division setting is displayed" + Cr + 
            "\ton top of the graph." + Cr + Cr +
            "\tOn the " + USBscope50_Main.productID + " there is a red led which should be " + Cr + 
            "\tpulsing if " + USBscope50_Main.productID + " is plugged in and software is running." + Cr +
            "\tBelow this red LED is a PCB section poking out and " + Cr +
            "\tat the end of it is a round pad with COMP label. " + Cr +
            "\tAttach probe to comp pad." + Cr + Cr +
            "\tLook for a comp button on the Ch1 tab on the software." + Cr +
            "\tClick on it, the button should change colour, comp is on." + Cr + Cr +
            "\tEither select Run->Run menu option or click on shortcut button" + Cr +
            "\tRun in the toolbar. " + Cr + Cr +
            "\tYou should observe square wave being displayed " + Cr +
            "\tand at this point if necessary you could " + Cr +
            "\tadjust your probe compensation." + Cr + Cr +
            "\tHope you enjoy using " + USBscope50_Main.productID + "." + Cr + Cr + "\t" + USBscope50_Main.companyID);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        TutorialClose.setText("CLOSE");
        TutorialClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(TutorialClose, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TutorialClose))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TutorialCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialCloseActionPerformed
        //USBscope50_Main.TutorialSaveGraphDisplayed = false;
        this.setVisible(false);
}//GEN-LAST:event_TutorialCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (USBscope50_Main.companyID.equals("PRIST")){
            this.setIconImage(AKIPLogo.getImage());
        }else{
            this.setIconImage(ElanLogo.getImage());
        }
        jTextArea1.setCaretPosition(0);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //USBscope50_Main.TutorialSaveGraphDisplayed = false;
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new Tutorial().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TutorialClose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
